### PR TITLE
added social media icons

### LINKED ISSUE #1: Add icons to the social media links in the footer
Maybe we can try icons by font awesome.

This is a beginner friendly issue. Let a first year take this up. @knrt10

### PR DESCRIPTION
**Pull request by debck**
Fixes #1

### CODE REVIEW

**Comment by debck** [comment]
The git log is pissed sorry for the mistake ..can i just another PR for same @knrt10

**Comment by palash25** [comment]
> The git log is pissed sorry for the mistake ..can i just make another PR for same @knrt10

We can help you with git but try to do this in the same PR or else you will never learn.

And if the log turns out to be beyond fixing then you can start another PR 
:+1:

**Comment by palash25** [comment]
This is a good commit message
```
<name-of-the-file-or-part-of-the-codebase-that-was-changed>: A short description

A long description if needed

Closes: <issue-link>
```

**Comment by palash25** [comment]
You can use the amend flag to amend your commits
```
git commit --amend
```

**Comment by debck** [comment]
Sorry @palash25  i somehow deleted the branch trying to change something.
Will learn then again make a PR

**Comment by debck** [comment]
Finally its done 
Plz review

**Comment by knrt10** [comment]
@debck thank you for your contribution

**Pull request merged**
