### PR TITLE
Add Sibasish to contributors

### PR DESCRIPTION
**Pull request by sibasish14**

### CODE REVIEW

**Comment by shivank01** [comment]
@sibasish14 the photo size is larger than recommended. Therefore the card size of yours is larger than all others.

**Comment by shivank01** [comment]
@palash25 @knrt10 check this out.

**Comment by palash25** [comment]
@shivank01  thanks I should have been more careful while reviewing.

We will be adding a simple regex test to avoid such mistakes in the future.

**Comment by palash25** [comment]
look at others Profile.md and look at the url they have posted we want that.

make another PR

**Comment by sibasish14** [comment]
I guess now I don't need to create a new PR, right @palash25 ?
(because https://github.com/p-society/p-society.github.io/issues/64 will fix this)

**Comment by palash25** [comment]
Yes also merged PR can't be fixed so stop conversing on this thread. :wink:

**Pull request merged**
