### PR TITLE
added piyush to contributors

### PR DESCRIPTION
**Pull request by itsmepiyush2**

### CODE REVIEW

**Comment by palash25** [comment]
Wtf! why has @debck authored this commit?

**Comment by itsmepiyush2** [comment]
I did it using his laptop because I had already forked the repository and if I would have deleted and forked again, that would have been a mess. Did I do something wrong?

**Comment by itsmepiyush2** [comment]
@palash25 Actually, since I used @debck 's computer and pushed it using git bash and it was configured to his account, hence why it shows that he authored the commit.

**Comment by palash25** [comment]
I won't merge commits from other authors, your PR should only have your commits.

So please make another PR from your laptop

**Pull request closed without merging**
